
---
title: "multi - french"
author: "Imperial College"
---


```{r Task2-run-epiestim-1, echo = FALSE}
opts_chunk$set(fig.path='figs/task2/', fig.keep='high',
               dev=c('png'), fig.width=8, fig.height=5, cache=FALSE,
               tidy=FALSE, warning=FALSE, fig.show="asis"
 	       )


###########################################################################
###########################################################################

# get Rts for each locations and variants
# extract R matrix from epiestim and samples of posterior

get_epiestim_rt_multi_Locations <- function(I , Epi_param){
  
  t_start <- seq(2, nrow(I[[1]])-(Epi_param$t_window-1)) 
  t_end <- t_start + (Epi_param$t_window-1)
  trim_time <- which(cumsum(Epi_param$SI) >= Epi_param$threshold_SI_initial_incidence)[1]
  
  EpiEstim_Rt <- list()
  template <- I[[1]]
  template[,2:ncol(template)] <- NA
  
  for (k in 1:length(I)){
    
    EpiEstim_Rt[[ names(I)[k] ]] <- list(Rt_m = template,
                                         Rt_low = template,
                                         Rt_up = template,
                                         Rt_incl = template,
                                         Rt_s = array(NA,dim = c(nrow(I[[k]]), ncol(I[[k]])-1, Epi_param$n_sample_R)),
                                         Rt_mean = template,
                                         Rt_std = template)
    
    
    for(i in 2:ncol(I[[k]]) ){
      
      temp <- EpiEstim::estimate_R(incid = I[[k]][,i], 
                                   method = "non_parametric_si", 
                                   config = EpiEstim::make_config(list(si_distr = Epi_param$SI,
                                                                       t_start = t_start ,
                                                                       t_end = t_end,
                                                                       mean_prior = Epi_param$mean_prior_Rt,
                                                                       std_prior = Epi_param$std_prior_Rt)))
      
      EpiEstim_Rt[[ names(I)[k] ]]$Rt_m[temp$R$t_end,i] <- temp$R$`Median(R)`
      EpiEstim_Rt[[ names(I)[k] ]]$Rt_low[temp$R$t_end,i] <- temp$R$`Quantile.0.025(R)`
      EpiEstim_Rt[[ names(I)[k] ]]$Rt_up[temp$R$t_end,i] <- temp$R$`Quantile.0.975(R)`
      EpiEstim_Rt[[ names(I)[k] ]]$Rt_mean[temp$R$t_end,i] <- temp$R$`Mean(R)`
      EpiEstim_Rt[[ names(I)[k] ]]$Rt_std[temp$R$t_end,i] <- temp$R$`Std(R)`
      
      incl <- which( ((EpiEstim_Rt[[ names(I)[k] ]]$Rt_up[,i] - 
                        EpiEstim_Rt[[ names(I)[k] ]]$Rt_low[,i]) <= 
                       Epi_param$threshold_Rt_95width) )
      f <- which(incl < (temp$R$t_end[1] + trim_time))
      if(length(f)>0){
        incl <- incl[-f]
      }
      EpiEstim_Rt[[ names(I)[k] ]]$Rt_incl[incl,i] <- 1
      
      #samples
      temp2 <- matrix(NA, nrow = nrow(I[[k]]),
                      ncol = Epi_param$n_sample_R)
      for(j in incl){
        mu <- EpiEstim_Rt[[ names(I)[k] ]]$Rt_mean[j,i]
        std <- EpiEstim_Rt[[ names(I)[k] ]]$Rt_std[j,i]
        param <- epitrix::gamma_mucv2shapescale(mu = mu,
                                               cv = std/mu)
        temp2[j,] <- rgamma(n = Epi_param$n_sample_R, shape = param$shape, scale = param$scale)
      }
      
      EpiEstim_Rt[[ names(I)[k] ]]$Rt_s[,i-1,] <- temp2
    }
  }
  
  return(EpiEstim_Rt)
}


###########################################################################
###########################################################################

```

# load data

```{r Task2-run-epiestim-2}

Epi_param <- readRDS('Epi_param.rds')

I_fr <- readRDS(file = 'I_fr.rds')
I_UK1 <- readRDS(file = 'I_UK1.rds')
I_UK2 <- readRDS(file = 'I_UK2.rds')

periods <- readRDS('periods.rds')

```

# run epiestim

## run epiestim on french data

```{r Task2-run-epiestim-3}

Rt_epi_fr <- get_epiestim_rt_multi_Locations(I = I_fr , Epi_param = Epi_param)


Rt_epi_fr$alpha$Rt_incl[,10]
```


## run epiestim on UK data

```{r Task2-run-epiestim-4}

Rt_epi_UK1 <- get_epiestim_rt_multi_Locations(I = I_UK1 , Epi_param = Epi_param)
Rt_epi_UK2 <- get_epiestim_rt_multi_Locations(I = I_UK2 , Epi_param = Epi_param)


Rt_epi_UK1$alpha$Rt_incl[,2]

```

# naive epsilon

## function

```{r Task2-run-epiestim-5}


naive_epsilon <- function(I, Rt_epi, periods){
  
  name_epsi <- c('All',colnames(I[[1]][-1]),paste0('Quarter ',1:4))
  epsi_template <- data.frame(name = name_epsi,
                              med = NA,
                              low = NA,
                              up = NA)
  
  
  epsilons_samples <- list()
  sum_epsilon <- list()
  for (i in 1:(length(I)-1)){
    sum_epsilon[[ paste(names(I)[c(1,i+1)],collapse='_') ]] <- epsi_template
    epsilons_samples[[ paste(names(I)[c(1,i+1)],collapse='_') ]] <- 1
  }
  
  epsilon <- list(sum_epsilon = sum_epsilon,
                  epsilons_samples = epsilons_samples)
  
  x <- Rt_epi
  x1 <- x[[1]]$Rt_s
  for(i in 1:dim(x1)[3]){
    x1[,,i] <- as.matrix(x1[,,i]*x[[1]]$Rt_incl[,-1])
  }
  for (k in 1:length(epsilon$sum_epsilon)){
    
    x2 <- x[[k+1]]$Rt_s
    for(i in 1:dim(x1)[3]){
      x2[,,i] <- as.matrix(x2[,,i]*x[[k+1]]$Rt_incl[,-1])
    }
    
    epsi1 <- x2/x1
    sum_epsi_geo <- apply(epsi1,2,quantile,c(.5,.025,.975),na.rm=TRUE)
    sum_epsi_national <- quantile(epsi1,c(.5,.025,.975),na.rm=TRUE)
    
    # # geo
    # for(i in 2:ncol(I[[1]])){
    #   epsilon$sum_epsilon[[k]][i,2:4] <- quantile(epsi1[,i-1,],c(.5,.025,.975),na.rm=TRUE)
    # }
    
    # by quarter
    for(i in 1:4){
      f <- which(periods$periods == i)
      epsilon$sum_epsilon[[k]][ncol(I[[1]])+i,2:4]  <- quantile(epsi1[f,,],c(.5,.025,.975),na.rm=TRUE)
    }
    
    epsilon$sum_epsilon[[k]][1,2:4] <- t(sum_epsi_national)
    epsilon$sum_epsilon[[k]][2:ncol(I[[1]]),2:4] <- t(sum_epsi_geo)
    
    epsilon$epsilons_samples[[k]] <- epsi1
    
    
  }
  
  return(epsilon)
}

```

## france

```{r Task2-run-epiestim-6}

naive_epsilon_fr <- naive_epsilon(I = I_fr, 
                                  Rt_epi = Rt_epi_fr,
                                  periods = periods$periods_fr)

naive_epsilon_fr$sum_epsilon$wild_alpha
```

## UK1

```{r Task2-run-epiestim-7}

naive_epsilon_UK1 <- naive_epsilon(I = I_UK1,
                                   Rt_epi = Rt_epi_UK1,
                                   periods = periods$periods_UK1)

naive_epsilon_UK1$sum_epsilon$wild_alpha
I_fr[[1]]$date[periods$periods_fr$intervals]
```

## UK2


```{r Task2-run-epiestim-8}

naive_epsilon_UK2 <- naive_epsilon(I = I_UK2,
                                   Rt_epi = Rt_epi_UK2,
                                   periods = periods$periods_UK2)

naive_epsilon_UK2$sum_epsilon$alpha_delta

```




# save

```{r Task2-run-epiestim-9}

saveRDS(object = Rt_epi_fr, file = 'Rt_epi_fr.rds')
saveRDS(object = Rt_epi_UK1, file = 'Rt_epi_UK1.rds')
saveRDS(object = Rt_epi_UK2, file = 'Rt_epi_UK2.rds')

saveRDS(object = naive_epsilon_fr, file = 'naive_epsilon_fr.rds')
saveRDS(object = naive_epsilon_UK1, file = 'naive_epsilon_UK1.rds')
saveRDS(object = naive_epsilon_UK2, file = 'naive_epsilon_UK2.rds')

```
