---
title: "ccc"
author: "Pierre Nouvellet"
date: "2021-04"
---

```{r options, include = FALSE, message = FALSE, warning = FALSE, error = FALSE}
set.seed(1)
# runif(1,0,1)
library(knitr)
library(EpiEstim)

opts_chunk$set(collapse = TRUE)

opts_chunk$set(fig.path='figs/', fig.keep='high', 
               dev=c('png'), cache=FALSE,
               tidy=FALSE, warning=FALSE, fig.show="asis"
)

```



# simulated data not accounting for variant


```{r}

data_incidence <- readRDS('../simulations/incidence.rds')

SI_sim <- readRDS('../simulations/si.rds') 

target <- readRDS('../simulations/target_Rt.rds')


```

## prepare

```{r}
n_location <- as.integer(4)

I <- data_incidence[,c(1,3,2,4)]

t_window <- 7
t_start <- seq(2, nrow(I)-(t_window-1)) 
t_end <- t_start + (t_window-1)


## prior R
mean_prior <- c(2)
std_prior <- c(1)


```


```{r compare_daily_target}

par(mfrow = c(2, 2))

for(i in 1:4){
  
  daily_res <- estimate_R(incid = I[,i], 
                          method = "non_parametric_si", 
                          config = make_config(list(si_distr = SI_sim,
                                                    t_start = seq(2, nrow(I), 1),
                                                    t_end = seq(2, nrow(I), 1),
                                                    mean_prior = mean_prior,
                                                    std_prior = std_prior)))
  
  ### Plot daily EpiEstim
  col <- 'blue'
  plot(daily_res$R$t_start, daily_res$R$`Median(R)`,
        type = 'l', col = col,
       ylim = c(0,4), bty='none',
        xlab = '',ylab = 'R_t',
        main = names(target)[i])
  polygon(c(daily_res$R$t_start,rev(daily_res$R$t_start)), 
          c(daily_res$R$`Quantile.0.025(R)`,rev(daily_res$R$`Quantile.0.975(R)`)),
          border = NA, col = scales::alpha(col, 0.3))
  
  abline(h = 1, col = 'red3', lty = 2)
  
  ### Plot target
  lines(1:length(target[[i]]), target[[i]],
        lty = 2,col = 'black')
  
  if(i == 1) {
    legend('topright',
           c('target',
             'Daily EpiEstim'),
           lty = c(2, 1, 1, 1, 1),
           bty = 'n', col= c('black', 'blue'))
  }
}
```

```{r compare_weekly_target}

par(mfrow = c(2, 2))

for(i in 1:4){
  
  weekly_res <- estimate_R(incid = I[,i], 
                           method = "non_parametric_si", 
                           config = make_config(list(si_distr = SI_sim,
                                                     t_start = t_start,
                                                     t_end = t_end,
                                                     mean_prior = mean_prior,
                                                     std_prior = std_prior)))
  
  x_epi_start <- weekly_res$R$t_start # weekly_res$R$t_end #(weekly_res$R$t_start + weekly_res$R$t_end)/2 # 
  x_epi_end <- weekly_res$R$t_end #(weekly_res$R$t_start + weekly_res$R$t_end)/2 # 
  x_epi_mid <- (weekly_res$R$t_start + weekly_res$R$t_end)/2 # 

  ### Plot weekly EpiEstim
  # plot weekly EpiEstim at start of time window
  col <- 'red3'
  plot(x_epi_start, weekly_res$R$`Median(R)`,
       type = 'l',col = col,
       ylim = c(0,4), bty='none',
       xlab = '',ylab = 'R_t',
       main = names(target)[i])
  polygon(c(x_epi_start,rev(x_epi_start)),
          c(weekly_res$R$`Quantile.0.025(R)`,rev(weekly_res$R$`Quantile.0.975(R)`)),
          border = NA, col = scales::alpha(col, 0.3))
  # end of time window
  col <- 'gold'
  lines(x_epi_end, weekly_res$R$`Median(R)`,
        type = 'l', col = col)
  polygon(c(x_epi_end,rev(x_epi_end)),
          c(weekly_res$R$`Quantile.0.025(R)`,rev(weekly_res$R$`Quantile.0.975(R)`)),
          border = NA, col = scales::alpha(col, 0.3))
  # mid of time window
  col <- 'orange'
  lines(x_epi_mid, weekly_res$R$`Median(R)`,
        type = 'l', col = col)
  polygon(c(x_epi_mid,rev(x_epi_mid)),
          c(weekly_res$R$`Quantile.0.025(R)`,rev(weekly_res$R$`Quantile.0.975(R)`)),
          border = NA, col = scales::alpha(col, 0.3))

  abline(h = 1, col = 'red3', lty = 2)
  
  
  
  ### Plot target
  lines(1:length(target[[i]]), target[[i]],
        lty = 2,col = 'black')
  
  if(i == 1) {
    legend('topright',
           c('target',
             'Weekly EpiEstim (start)','Weekly EpiEstim (mid)','Weekly EpiEstim (end)'),
           lty = c(2, 1, 1, 1, 1),
           bty = 'n', col= c('black','red3', 'orange', 'gold'))
  }
}
```

