---
title: "ccc"
author: "Pierre Nouvellet"
date: "2021-04"
---

```{r options, include = FALSE, message = FALSE, warning = FALSE, error = FALSE}
set.seed(1)
# runif(1,0,1)
library(knitr)
library(EpiEstim)

opts_chunk$set(collapse = TRUE)

opts_chunk$set(fig.path='figs/', fig.keep='high', 
               dev=c('png'), cache=FALSE,
               tidy=FALSE, warning=FALSE, fig.show="asis"
)

```



# simulated data not accounting for variant


```{r}

rm(list = ls())

```


```{r}

data_incidence <- readRDS('../simulations/incidence.rds')
data_incidence <- data_incidence[4:99,]
SI_sim <- readRDS('../simulations/si.rds') 

```

## prepare

```{r}
n_location <- as.integer(4)
# n_variant <- as.integer(2)
I <- data_incidence[,c(1,3,2,4)]

t_start <- seq(2, nrow(I)-6) 
t_end <- t_start + 6

# preprocessed

O_I <- apply(I,2,EpiEstim::overall_infectivity, si_distr = SI_sim)

mI <- array(NA, dim = c( n_location,
                         length(t_start),
                         ncol = t_end[1] - t_start[1]+1) )
m_O_I <- mI
for(k in 1:(n_location)){
  for(i in 1:dim(mI)[2]){
    mI[k,i,] <- I[t_start[i]:t_end[i],k]
    m_O_I[k,i,] <- O_I[t_start[i]:t_end[i],k]
  }
}
useful <- (rep(1,dim(mI)[3]))


## prior R
mean_prior <- c(2)
std_prior <- c(1)

param_gamma <- epitrix::gamma_mucv2shapescale(mu = mean_prior,
                                              cv = std_prior/mean_prior)

```


```{r}

for(i in 1:4){
  
  param_gamma <- epitrix::gamma_mucv2shapescale(mu = mean_prior,
                                                cv = std_prior/mean_prior)
  
  res <- estimate_R(incid = I[,i], 
                    method = "non_parametric_si", 
                    config = make_config(list(si_distr = SI_sim,
                                              t_start = t_start,
                                              t_end = t_end,
                                              mean_prior = mean_prior,
                                              std_prior = std_prior)))
  
  
  ## rstan
  standata <- list(nR = dim(mI)[2],
                   tw = dim(mI)[3],
                   I = mI[i,,],
                   O_I = m_O_I[i,,],
                   U = useful,
                   prior_alpha = param_gamma$shape,
                   prior_beta = 1/param_gamma$scale)
  
  fit <- rstan::stan(file = 'epi_estim.stan', data = standata)
  samples <- rstan::extract(fit)
  
  sum_Rt <- apply(samples$Rt,2,quantile,c(.5,.025,.975))
  
  
  # plot results
  # par(mar = c(bottom, left, top, right)), default  c(5.1, 4.1, 4.1, 2.1).
  par(mar = c(3,4,2,2),cex=1)
  
  
  x <- (res$R$t_start + res$R$t_end)/2
  # x <- Flu2009$incidence$dates[x]
  
  plot(x, sum_Rt[1,], bty = 'n',
       type = 'l',col = 'blue3',
       ylim = c(0,4), bty='none',
       xlab = '',ylab = 'R_t',
       main = paste0('Prior: mean = ',mean_prior,', sd = ',std_prior))
  polygon(c(x,rev(x)), 
          c(sum_Rt[3,],rev(sum_Rt[2,])),
          border = NA,col = rgb(0,0,1,.1))
  abline(h = 1, col = 'red3', lty = 2)
  
  lines(x, res$R$`Median(R)`,
        type = 'l',col = 'red3')
  polygon(c(x,rev(x)), 
          c(res$R$`Quantile.0.025(R)`,rev(res$R$`Quantile.0.975(R)`)),
          border = NA,col = rgb(1,0,0,.1))
  
  legend('topright',c('stan','EpiEstim'),lwd=2,
         bty = 'n', col= c('blue3','red3'))
  
  
}
```

