---
title: "ccc"
author: "Pierre Nouvellet"
date: "2021-04"
---

```{r options, include = FALSE, message = FALSE, warning = FALSE, error = FALSE}
set.seed(1)
# runif(1,0,1)
library(knitr)

opts_chunk$set(collapse = TRUE)

opts_chunk$set(fig.path='figs/', fig.keep='high', 
               dev=c('png'), cache=FALSE,
               tidy=FALSE, warning=FALSE, fig.show="asis"
)

```

# test multi locations/variants with repeated flu incidence

```{r}

library(EpiEstim)
data("Flu2009")

SI <- EpiEstim::discr_si(0:20, 2.6, 1.5)

I0 <- Flu2009$incidence$I

n_location <- 2
n_variant <- 2
I <- matrix(rep(I0,each = n_location*n_variant),
            nrow = length(I0),
            ncol = n_location*n_variant, byrow = TRUE)

t_start <- seq(2, nrow(Flu2009$incidence)-6) 
t_end <- t_start + 6



```

# Rstan

### preparing model

```{r}


# stan

O_I <- apply(I,2,EpiEstim::overall_infectivity, si_distr = SI)

mI <- array(NA, dim = c( n_location*n_variant,
                         length(t_start),
                         ncol = t_end[1] - t_start[1]+1) )
m_O_I <- mI
for(k in 1:(n_location*n_variant)){
  for(i in 1:dim(mI)[2]){
    mI[k,i,] <- I[t_start[i]:t_end[i]]
    m_O_I[k,i,] <- O_I[t_start[i]:t_end[i]]
  }
}
useful <- (rep(1,dim(mI)[3]))

```

### running 1 model

```{r}
mean_prior <- c(2)
std_prior <- c(1)

param_gamma <- epitrix::gamma_mucv2shapescale(mu = mean_prior,
                                              cv = std_prior/mean_prior)

x<- seq(0,10,length.out = 1e2)
plot(x, dgamma(x = x, 
               shape = param_gamma$shape, 
               scale = param_gamma$scale))
```


```{r}

## rstan
standata <- list(nt = as.integer(dim(mI)[2]),
                 tw = as.integer(dim(mI)[3]),
                 n_location = n_location,
                 n_variant = n_variant,
                 I = mI,
                 O_I = m_O_I,
                 U = useful,
                 prior_shape = param_gamma$shape,
                 prior_rate = 1/param_gamma$scale,
                 prior_beta = 10)


fit <- rstan::stan(file = 'ML_epi_estim_v0.stan', data = standata)
samples <- rstan::extract(fit)

sum_Rt <- list()
for(i in 1:(n_location)){
  sum_Rt[[i]] <- apply(samples$Rt[,,i],2,quantile,c(.5,.025,.975))
}
sum_beta <- apply(samples$Beta,2,quantile,c(.5,.025,.975))

```



```{r}

x <- seq(1,ncol(sum_Rt[[1]]))

for (i in 1:(n_location)){
  
  plot(x, sum_Rt[[i]][1,], bty = 'n',
       type = 'l',col = 'blue3',
       ylim = c(0,4), bty='none',
       xlab = '',ylab = 'R_t')
  polygon(c(x,rev(x)), 
          c(sum_Rt[[i]][3,],rev(sum_Rt[[i]][2,])),
          border = NA,col = rgb(0,0,1,.1))
  abline(h = 1, col = 'red3', lty = 2)
  
  
}

Hmisc::errbar(1:n_variant, 
              y = sum_beta[1,],
              yplus = sum_beta[2,], 
              yminus = sum_beta[3,],
              ylim = c(0,2),xlim = c(.5,n_variant+.5))

abline(h = 1, col = 'red3', lty = 2)

```

# simulated data

```{r}

rm(list = ls())

```


```{r}

data_incidence <- readRDS('../simulations/incidence.rds')
data_incidence <- data_incidence[4:99,]
SI_sim <- readRDS('../simulations/si.rds') 

```

## prepare

```{r}
n_location <- as.integer(2)
n_variant <- as.integer(2)
I <- data_incidence[,c(1,3,2,4)]

t_start <- seq(2, nrow(I)-6) 
t_end <- t_start + 6

# preprocessed

O_I <- apply(I,2,EpiEstim::overall_infectivity, si_distr = SI_sim)

mI <- array(NA, dim = c( n_location*n_variant,
                         length(t_start),
                         ncol = t_end[1] - t_start[1]+1) )
m_O_I <- mI
for(k in 1:(n_location*n_variant)){
  for(i in 1:dim(mI)[2]){
    mI[k,i,] <- I[t_start[i]:t_end[i],k]
    m_O_I[k,i,] <- O_I[t_start[i]:t_end[i],k]
  }
}
useful <- (rep(1,dim(mI)[3]))


## prior R
mean_prior <- c(2)
std_prior <- c(1)

param_gamma <- epitrix::gamma_mucv2shapescale(mu = mean_prior,
                                              cv = std_prior/mean_prior)


## rstan file
standata <- list(nt = as.integer(dim(mI)[2]),
                 tw = as.integer(dim(mI)[3]),
                 n_location = n_location,
                 n_variant = n_variant,
                 I = mI,
                 O_I = m_O_I,
                 U = useful,
                 prior_shape = param_gamma$shape,
                 prior_rate = 1/param_gamma$scale,
                 prior_beta = 10)



```

## fit

```{r}



fit <- rstan::stan(file = 'ML_epi_estim_v0.stan', data = standata)
samples <- rstan::extract(fit)

sum_Rt <- list()
for(i in 1:(n_location)){
  sum_Rt[[i]] <- apply(samples$Rt[,,i],2,quantile,c(.5,.025,.975))
}
sum_beta <- apply(samples$Beta,2,quantile,c(.5,.025,.975))

```

## plot


```{r}


x <- seq(1,ncol(sum_Rt[[1]]))

for (i in 1:(n_location)){
  
  plot(x, sum_Rt[[i]][1,], bty = 'n',
       type = 'l',col = 'blue3',
       ylim = c(0,4), bty='none',
       xlab = '',ylab = 'R_t')
  polygon(c(x,rev(x)), 
          c(sum_Rt[[i]][3,],rev(sum_Rt[[i]][2,])),
          border = NA,col = rgb(0,0,1,.1))
  abline(h = 1, col = 'red3', lty = 2)
  
  
}

Hmisc::errbar(1:n_variant, 
              y = sum_beta[1,],
              yplus = sum_beta[2,], 
              yminus = sum_beta[3,],
              ylim = c(0,2),xlim = c(.5,n_variant+.5))

abline(h = 1, col = 'red3', lty = 2)
# abline(h = 1.5, col = 'blue3', lty = 2)



plot(data_incidence[,1+1])

  lines(data_incidence[,3+1])

```

