---
title: "ccc"
author: "Pierre Nouvellet"
date: "2021-04"
---

```{r options, include = FALSE, message = FALSE, warning = FALSE, error = FALSE}
set.seed(1)
# runif(1,0,1)
library(knitr)

opts_chunk$set(collapse = TRUE)

opts_chunk$set(fig.path='figs/', fig.keep='high', 
               dev=c('png'), cache=FALSE,
               tidy=FALSE, warning=FALSE, fig.show="asis"
)

# rstan_options(auto_write = true)
```


# simulated data

```{r}

rm(list = ls())

```


```{r}


data_incidence <- readRDS('../simulations/incidence_min1.rds')
T_max <- nrow(data_incidence) # 60
SI_sim <- readRDS('../simulations/si.rds') 

```

## prepare

```{r}
n_location <- as.integer(2)
n_variant <- as.integer(2)
I <- data_incidence[,c(1,3,2,4)]

# preprocessed

O_I <- apply(I,2,EpiEstim::overall_infectivity, si_distr = SI_sim)

#eliminate early days
I <- I[5:T_max,]
O_I <- O_I[5:T_max,]


# time windows
t_start <- seq(2, nrow(I)-6) 
t_end <- t_start + 6

# array formulation

mI <- array(NA, dim = c( n_location*n_variant,
                         length(t_start),
                         ncol = t_end[1] - t_start[1]+1) )
m_O_I <- mI
for(k in 1:(n_location*n_variant)){
  for(i in 1:dim(mI)[2]){
    mI[k,i,] <- I[t_start[i]:t_end[i],k]
    m_O_I[k,i,] <- O_I[t_start[i]:t_end[i],k]
  }
}
useful <- (rep(1,dim(mI)[3]))


## prior R
mean_prior <- c(2)
std_prior <- c(1)

param_gamma <- epitrix::gamma_mucv2shapescale(mu = mean_prior,
                                              cv = std_prior/mean_prior)


## rstan file
standata <- list(nt = as.integer(dim(mI)[2]),
                 tw = as.integer(dim(mI)[3]),
                 n_location = n_location,
                 n_variant = n_variant,
                 I = mI,
                 O_I = m_O_I,
                 U = useful,
                 prior_shape = param_gamma$shape,
                 prior_rate = 1/param_gamma$scale,
                 prior_beta = 10)



```

## fit

```{r}



fit <- rstan::stan(file = 'ML_epi_estim_v0.stan',
                   data = standata,
                   control = list(max_treedepth = 15),
                   chains = 1)

samples <- rstan::extract(fit)

sum_Rt <- list()
for(i in 1:(n_location)){
  sum_Rt[[i]] <- apply(samples$Rt[,,i],2,quantile,c(.5,.025,.975))
}
sum_beta <- apply(samples$Beta,2,quantile,c(.5,.025,.975))

```

# epiestim

```{r}
res <- list()
for (i in 1:ncol(I)){
  
  res[[i]] <- EpiEstim::estimate_R(incid = I[,i],
                    method = "non_parametric_si",
                    config = EpiEstim::make_config(list(si_distr = SI_sim,
                                              t_start = t_start,
                                              t_end = t_end,
                                              mean_prior = mean_prior,
                                              std_prior = std_prior)))
}
```



## plot


```{r}
sum_Rt_variant <- list()
for(i in 1:(n_location)){
  temp <- samples$Rt[,,i] * (samples$beta %*% matrix(1,nrow = 1,ncol = ncol( samples$Rt[,,i])) )
  sum_Rt_variant[[i]] <- apply(temp,2,quantile,c(.5,.025,.975))
}

x <- seq(1,ncol(sum_Rt[[1]]))

for (i in 1:(n_location)){
  
  plot(x, sum_Rt[[i]][1,], bty = 'n',
       type = 'l',col = 'blue3',
       ylim = c(0,4), bty='none',
       xlab = '',ylab = 'R_t')
  polygon(c(x,rev(x)), 
          c(sum_Rt[[i]][3,],rev(sum_Rt[[i]][2,])),
          border = NA,col = rgb(0,0,1,.1))
  
  # other variant
  lines(x, sum_Rt_variant[[i]][1,], col = 'red3') 
  
  polygon(c(x,rev(x)), 
          c(sum_Rt_variant[[i]][3,],rev(sum_Rt_variant[[i]][2,])),
          border = NA,col = rgb(1,0,0,.1))
  
  abline(h = 1, col = 'red3', lty = 2)
  
  # plot epiestim
  index_epiepestim <- (i-1)*n_location+1
  lines(x, res[[index_epiepestim]]$R$`Median(R)`,
        lty = 2,col = 'blue3')
  polygon(c(x,rev(x)), 
          c(res[[index_epiepestim]]$R$`Quantile.0.025(R)`,
            rev(res[[index_epiepestim]]$R$`Quantile.0.975(R)`)),
          border = rgb(0,0,1), col = rgb(0,0,1,.05))
  
  lines(x, res[[index_epiepestim+1]]$R$`Median(R)`,
        lty = 2,col = 'red3')
  polygon(c(x,rev(x)), 
          c(res[[index_epiepestim+1]]$R$`Quantile.0.025(R)`,
            rev(res[[index_epiepestim+1]]$R$`Quantile.0.975(R)`)),
          border = rgb(1,0,1), col = rgb(1,0,0,.05))

  
}

Hmisc::errbar(1:n_variant, 
              y = sum_beta[1,],
              yplus = sum_beta[2,], 
              yminus = sum_beta[3,],
              ylim = c(0,2),xlim = c(.5,n_variant+.5))

abline(h = 1, col = 'red3', lty = 2)
abline(h = 1.5, col = 'blue3', lty = 2)


# 
# plot(data_incidence[,1+1])
# 
#   lines(data_incidence[,3+1])

```


