---
title: "ccc"
author: "Pierre Nouvellet"
date: "2021-04"
---

```{r options, include = FALSE, message = FALSE, warning = FALSE, error = FALSE}
set.seed(1)
# runif(1,0,1)
library(knitr)
library(EpiEstim)

opts_chunk$set(collapse = TRUE)

opts_chunk$set(fig.path='figs/', fig.keep='high', 
               dev=c('png'), cache=FALSE,
               tidy=FALSE, warning=FALSE, fig.show="asis"
)

```



# simulated data not accounting for variant


```{r}
#data <- readRDS('EpiEstim.rds')
incid <- readRDS('../simulations/incidence.rds')
SI_sim <- readRDS('../simulations/si.rds') 
target <- readRDS('../simulations/target_Rt.rds')

```

# load new package

```{r}

devtools::load_all("../MultiLocEpiEstim/")
?estimate_joint
```

## prepare data

```{r}
n_t <- dim(incid)[1]
n_loc <- dim(incid)[2]
n_v <- dim(incid)[3]

priors <- default_priors()

# arbitrary serial interval, same for both variants
w_v <- SI_sim
w <- cbind(w_v, w_v)

system.time(
res <- estimate_joint(incid, w, priors,
                    n_iter = 8000,
                    burnin = 3000)
)

par(mfrow = c(2, 2))
plot(res$epsilon, type = "l", xlab = "Iterations", ylab = "Epsilon")
plot(res$R[50,1,], , type = "l",
     xlab = "Iterations", ylab = "Rt time 50 location 1")
plot(res$R[50,2,], , type = "l",
     xlab = "Iterations", ylab = "Rt time 50 location 2")
plot(res$R[50,3,], , type = "l",
     xlab = "Iterations", ylab = "Rt time 50 location 3")

```

# fit model

```{r}


sum_Rt <- list()
for(i in 1:(n_loc)){
  sum_Rt[[i]] <- apply(res$R[,i,],1,quantile,c(.5,.025,.975),na.rm = TRUE)
}
sum_beta <- quantile(res$epsilon,c(.5,.025,.975))

sum_Rt_variant <- list()
for(i in 1:(n_loc)){
  temp <-  t(res$R[,i,]) *(res$epsilon %*% matrix(1,nrow = 1,ncol = nrow( res$R[,i,])) )
  sum_Rt_variant[[i]] <- apply(temp,2,quantile,c(.5,.025,.975),na.rm=TRUE)
}


sum_Rt <- list(sum_Rt[[1]],sum_Rt_variant[[1]],
               sum_Rt[[2]],sum_Rt_variant[[2]])
```

# check output

```{r}
par(mfrow = c(2, 2))

x_epi_start <- data$weekly_Rt_EpiEstim[[1]]$R$t_start 
x_epi_end <- data$weekly_Rt_EpiEstim[[1]]$R$t_end 
x_epi_mid <- (x_epi_start + x_epi_end)/2 
x <- seq(1,nrow(data_incidence))

for (i in 1:(n_loc*n_v)){
  
  # Plot weekly EpiEstan
  
  col <- 'red3'
  plot(x, sum_Rt[[i]][1,],
       type = 'l',col = col,
       ylim = c(0,4), bty='none',
       xlab = '',ylab = 'R_t',
       main = names(data$target)[i])
  polygon(c(x,rev(x)),
          c(sum_Rt[[i]][2,],rev(sum_Rt[[i]][3,])),
          border = NA, col = scales::alpha(col, 0.3))
  

  # mid of time window
  col <- 'orange'
  lines(x_epi_mid, data$weekly_Rt_EpiEstim[[i]]$R$`Median(R)`,
        type = 'l', col = col)
  polygon(c(x_epi_mid,rev(x_epi_mid)),
          c(data$weekly_Rt_EpiEstim[[i]]$R$`Quantile.0.025(R)`,
            rev(data$weekly_Rt_EpiEstim[[i]]$R$`Quantile.0.975(R)`)),
          border = NA, col = scales::alpha(col, 0.3))

  abline(h = 1, col = 'red3', lty = 2)
  
  
  
  ### Plot target
  lines(1:length(data$target[[i]]), data$target[[i]],
        lty = 2,col = 'black')
  
  if(i == 1) {
    legend('topright',
           c('target',
             'new EpiEstim (variant)','Weekly EpiEstim (mid)'),
           lty = c(2, 1, 1, 1, 1),
           bty = 'n', col= c('black','red3', 'orange'))
  }
  
  
}

```

