
---
title: "multi - french"
author: "Imperial College"
---


```{r echo = FALSE}
library(knitr)
opts_chunk$set(fig.path='figs/', fig.keep='high',
               dev=c('png'), fig.width=8, fig.height=5, cache=FALSE,
               tidy=FALSE, warning=FALSE, fig.show="asis"
 	       )
# library(EpiEstim)
# library(Hmisc)
# library(dplyr)
# library(tidyr)
library(EpiEstim)
library(ggplot2)
library(yarrr)
library(tidyverse)

source('Rscript/utils.r')
source('Rscript/wrapper.r')

library(RColorBrewer)
rf <- colorRampPalette(rev(brewer.pal(8,'Spectral')))
r <- rf(32)
```

# load data

```{r}
variants <- list()
variants[[1]]<- c('wild','alpha')
variants[[2]]<- c('alpha','delta')

dataset <- length(variants)

## read in england data
england <- readRDS("Rdata/Rdata_eng/s_by_region_over25_pillar2_pcr.rds")
england <- england %>%
  select(specimen_date, nhser_name,
         s_positive_adj1, s_negative_adj1, s_na_adj1) %>%
  group_by(specimen_date, nhser_name) %>%
  summarise(s_positive_adj1 = sum(s_positive_adj1),
            s_negative_adj1 = sum(s_negative_adj1),
            s_na_adj1 = sum(s_na_adj1)) %>%
  mutate(region = tolower(gsub(" ", "_", nhser_name))) %>%
  rename(date = specimen_date)

## there are some samples not identified as negative or positive, we split those
## according to the ratio of the two. In the hopefully rare case that none are
## identified as negative or positive, these are split 50/50 - probably another
## way could be better?
na_positive_prop <- england$s_positive_adj1 /
  (england$s_positive_adj1 + england$s_negative_adj1)
na_positive_prop <- ifelse(is.na(na_positive_prop), 0.5, na_positive_prop)
s_positive_adj1_extra <- round(na_positive_prop * england$s_na_adj1)
s_negative_adj1_extra <- england$s_na_adj1 - s_positive_adj1_extra
england$s_positive_adj1 <- england$s_positive_adj1 + s_positive_adj1_extra
england$s_negative_adj1 <- england$s_negative_adj1 + s_negative_adj1_extra

d <- list( alpha = england[which((england$date >= as.Date('01/09/2020', 
                                                          format = '%d/%m/%Y')) &
                                   (england$date < as.Date('15/03/2021', 
                                                           format = '%d/%m/%Y'))),],
           delta = england[which(england$date >= as.Date('15/03/2021', 
                                                         format = '%d/%m/%Y')),])


names(d[[1]])[3:4] <- c('wild','alpha')
names(d[[2]])[3:4] <- c('delta','alpha')

```



# get list of matrix, 1 for each variant with 1 column for dates and 'n' columns for each location


```{r,eng_incidence}
# for incidence
regions <- sort(unique(d[[1]]$region))
#for Rt
mean_prior <- c(2)
std_prior <- c(1)
#
mean_SI <- 5.4 # mean 5.4 days and standard deviation of 1.5 days (Rai, Shukla, and Dwivedi 2021).
std_SI <- 1.5
SI <- EpiEstim::discr_si(seq(0, 20), mean_SI, std_SI)
t_window <- 7
n_sample_R <- 1e2

initial_res <- list()

for (i in 1:dataset){
  initial_res[[i]] <- wrapper(dat = d[[i]] , regions = regions, plot_incidence = TRUE,
                         variants = variants[[i]], t_window = t_window, 
                         SI = SI, mean_prior = mean_prior,
                         std_prior = std_prior, n_sample_R = n_sample_R) # trim initial Rt until cumsum(1:x)>=0.99
}

saveRDS(object = initial_res$I, file = 'Rdata/Incidence_england.rds')
```


# table looking at inclusion

days where 2 variants have Rt estimates with 95%CrI lower than 0.5

```{r, Rts_eng, fig.width=8, fig.height=5}

selection <- list()
for(i in 1:dataset){
  selection[[i]] <- select_Rt_get_median_samples(th = 0.5,  # width of Rt CrI included
                                            EpiEstim_Rt = initial_res[[i]]$EpiEstim_Rt,
                                            regions = regions, 
                                            variants = variants[[i]],
                                            SI = SI,
                                            trim = 0.99) # trim initial Rt until cumsum(1:x)>=0.99
  
  plot_Rt_post_selection(res = initial_res[[i]], selection = selection[[i]], 
                         regions = regions, variants = variants[[i]])
  
  selection$summary_select
  
  write.csv(selection[[i]]$summary_select, file = paste0('Rdata/selected_eng_',i,'.csv'))
}

```


```{r,plot_Rt_eng,  fig.width=5, fig.height=3}

for(i in 1:dataset){
  ep <- plot_hist_dist(x = selection[[i]]$samples_Rts,
                       x_sum = selection[[i]]$summary_select, 
                       keep=TRUE)
  
  # res_epsi <- data.frame(matrix(NA,ncol = 4, nrow = length(u_age) ))
  # names(res_epsi) <- c('Age_class', names(ep))
  # res_epsi$Age_class <- u_age
  # 
  # for(i in 1:3){
  #   temp <- round(quantile(ep[[i]],c(0.5,.025,.975)),digits = 2)
  #   res_epsi[length(u_age),1+i] <- paste0(temp[1],' ; 95%CrI[',temp[2],' ; ',temp[3],']')
  # }           
}
           
```



#check  3 variants


### prep for 1 dataset
```{r, joint_eng}
for(i in 1:dataset){
  incid <- array(NA,dim = c(nrow(initial_res[[i]]$I$alpha), length(regions), length(variants[[i]])))
  
  if(i==1){
    incid[,,1] <- as.matrix(initial_res[[i]]$I$wild[,-1])
    # temp <- as.matrix(initial_res$I$wild[,-1])
    incid[,,2] <- as.matrix(initial_res[[i]]$I$alpha[,-1])
  }else{
    incid[,,1] <- as.matrix(initial_res[[i]]$I$alpha[,-1])
    # temp <- as.matrix(initial_res$I$wild[,-1])
      incid[,,2] <- as.matrix(initial_res[[i]]$I$delta[,-1])
  }
  
  # SIs
  si_distr <- cbind(SI, SI, SI)
  priors <- default_priors()
  mcmc_control <- list(n_iter = 1e4L, burnin = 1e2L, thin = 10L) #default_mcmc_controls()
  
  t_start <- as.integer(which(cumsum(SI)>=.99)[1]+1)
  t_end <- as.integer(nrow(incid))
  n_intervals <- 4  
  
  
  ###inference
  
  
  Jestim_all <- wrapper_joint_Rt(incid = incid[,,],
                                 t_start = t_start, 
                                 t_end = t_end, 
                                 n_intervals = n_intervals, 
                                 plot_Rt = TRUE, 
                                 plot_epsilon_trace = TRUE,
                                 plot_epsilon = TRUE,
                                 initial_res = initial_res[[i]] )
  
  
  write.csv(Jestim_all$Sum_epsilon, file = paste0('Rdata/epsilons_eng_',i,'.csv'))
}     
```
