
---
title: "multi - french"
author: "Imperial College"
---


```{r echo = FALSE}
library(knitr)
opts_chunk$set(fig.path='figs/', fig.keep='high',
               dev=c('png'), fig.width=8, fig.height=5, cache=FALSE,
               tidy=FALSE, warning=FALSE, fig.show="asis"
 	       )
# library(EpiEstim)
# library(Hmisc)
# library(dplyr)
# library(tidyr)
library(EpiEstim)
library(ggplot2)
library(yarrr)

source('Rscript/utils.r')
source('Rscript/wrapper.r')

library(RColorBrewer)
rf <- colorRampPalette(rev(brewer.pal(8,'Spectral')))
r <- rf(32)
```

# load data

```{r}
variants <- list(c('wild','alpha','beta/gamma'))
dataset <- length(variants)


# from https://www.data.gouv.fr/fr/datasets/donnees-de-laboratoires-pour-le-depistage-indicateurs-sur-les-variants/

d <- read.csv(file = 'Rdata/Rdata_fr/sp-variant-7j-reg-2021-06-02-21h05.csv',sep=';')
d$reg <- as.character(d$reg)
d$cl_age90 <- as.character(d$cl_age90)
unique(d$cl_age90)
d$date <- as.Date(substr(d$semaine, 1, 10),format = '%Y-%m-%d')+6

# focus on all pop
d <- d[which(d$cl_age90 == '0'),]

# rename regions and remove 3
f <- which(d$reg %in% c('5','7','8'))
d <- d[-f,]

# from 
d_region <- read.csv(file = 'Rdata/Rdata_fr/regions-france.csv',encoding = "UTF-8")
d$region <- as.character(d_region$nom_region[match(d$reg,d_region$code_region)])
# unique(d$region)
# unique(d_region$code_region)
# sort(unique(d$reg))

# rename variants
variants0 <- c('Nb_susp_ABS','Nb_susp_501Y_V1','Nb_susp_501Y_V2_3')
# match(variants,names(d))


names(d) [match(variants0,names(d))]<- variants[[1]]
d <- list(fr = d)
```



# get list of matrix, 1 for each variant with 1 column for dates and 'n' columns for each location


```{r,france_incidence}
# for incidence
regions <- sort(unique(d[[1]]$region))
#for Rt
mean_prior <- c(2)
std_prior <- c(1)
#
mean_SI <- 5.4 # mean 5.4 days and standard deviation of 1.5 days (Rai, Shukla, and Dwivedi 2021).
std_SI <- 1.5
SI <- EpiEstim::discr_si(seq(0, 20), mean_SI, std_SI)
t_window <- 7
n_sample_R <- 1e2

initial_res <- list()

for (i in 1:dataset){
  initial_res[[i]] <- wrapper(dat = d[[i]] , regions = regions, plot_incidence = TRUE,
                         variants = variants[[i]], t_window = t_window, 
                         SI = SI, mean_prior = mean_prior,
                         std_prior = std_prior, n_sample_R = n_sample_R) # trim initial Rt until cumsum(1:x)>=0.99
}

saveRDS(object = initial_res$I, file = 'Rdata/Incidence_france.rds')
```


# table looking at inclusion

days where 2 variants have Rt estimates with 95%CrI lower than 0.5

```{r, Rts_fr, fig.width=8, fig.height=5}
selection <- list()
for(i in 1:dataset){
  selection[[i]] <- select_Rt_get_median_samples(th = 0.5,  # width of Rt CrI included
                                            EpiEstim_Rt = initial_res[[i]]$EpiEstim_Rt,
                                            regions = regions, 
                                            variants = variants[[i]],
                                            SI = SI,
                                            trim = 0.99) # trim initial Rt until cumsum(1:x)>=0.99
  
  plot_Rt_post_selection(res = initial_res[[i]], selection = selection[[i]], 
                         regions = regions, variants = variants[[i]])
  
  selection$summary_select
  
  write.csv(selection[[i]]$summary_select, file = paste0('Rdata/selected_fr_',i,'.csv'))
}

```


```{r,plot_Rt_fr,  fig.width=5, fig.height=8}

for(i in 1:dataset){
  ep <- plot_hist_dist(x = selection[[i]]$samples_Rts,
                       x_sum = selection[[i]]$summary_select, 
                       keep=TRUE)
  
  # res_epsi <- data.frame(matrix(NA,ncol = 4, nrow = length(u_age) ))
  # names(res_epsi) <- c('Age_class', names(ep))
  # res_epsi$Age_class <- u_age
  # 
  # for(i in 1:3){
  #   temp <- round(quantile(ep[[i]],c(0.5,.025,.975)),digits = 2)
  #   res_epsi[length(u_age),1+i] <- paste0(temp[1],' ; 95%CrI[',temp[2],' ; ',temp[3],']')
  # }           
}
           
```



#check  3 variants


### prep
```{r,joint_fr}
incid <- array(NA,dim = c(nrow(initial_res[[1]]$I$wild), 
                          length(regions), length(variants[[1]])))
incid[,,1] <- as.matrix(initial_res[[1]]$I$wild[,-1])
# temp <- as.matrix(initial_res$I$wild[,-1])
incid[,,2] <- as.matrix(initial_res[[1]]$I$alpha[,-1])
incid[,,3] <- as.matrix(initial_res[[1]]$I$`beta/gamma`[,-1])

# SIs
si_distr <- cbind(SI, SI, SI)
priors <- default_priors()
mcmc_control <- list(n_iter = 1e4L, burnin = 1e2L, thin = 10L) #default_mcmc_controls()

t_start <- as.integer(which(cumsum(SI)>=.99)[1]+1)
t_end <- as.integer(nrow(incid))
n_intervals <- 4  


###inference


Jestim_all <- wrapper_joint_Rt(incid = incid[,,],
                           t_start = t_start, 
                           t_end = t_end, 
                           n_intervals = n_intervals, 
                           plot_Rt = TRUE, 
                           plot_epsilon_trace = TRUE,
                           plot_epsilon = TRUE,
                           initial_res = initial_res[[1]] )


write.csv(Jestim_all$Sum_epsilon, file = 'Rdata/epsilons_fr.csv')
```

<!-- ```{r} -->
<!-- library(RColorBrewer) -->
<!-- rf <- colorRampPalette(rev(brewer.pal(8,'Spectral'))) -->
<!-- r <- rf(32) -->

<!-- for(i in 1:3){ -->
<!--   Rs <- array(NA,dim = dim(Jestim_all$R[[1]]$R)) -->
<!--   if(i ==1){ -->
<!--     e <-rep(1,dim(Rs)[3]) -->
<!--   }else{ -->
<!--     e <- Jestim_all$R[[1]]$epsilon[i-1,] -->
<!--   } -->
<!--   for (j in 1:length(regions)){ -->
<!--     Rs[,j,] <- Jestim_all$R[[1]]$R[,j,] * matrix(e, nrow = dim(Rs)[1], ncol = dim(Rs)[3], byrow = TRUE) -->
<!--   } -->


<!--   d_joint <- data.frame(date = initial_res$I$alpha$date, -->
<!--                    apply(Rs,c(1,2),median)) -->

<!--   names(d_joint) <- c('date',regions) -->

<!--   d_EpiEstim <- data.frame( date = initial_res$I[[1]]$date[initial_res$EpiEstim_Rt[[1]][[regions[1]]]$R$t_end], -->
<!--                     purrr::map_dfr(initial_res$EpiEstim_Rt[[variants[i]]], function(x) cbind(x$R$`Median(R)`))) -->
<!--   names(d_EpiEstim) <- c('date',regions) -->
<!--   d3 <- selection$select_Rt_by_variant[[i]] -->
<!--   d3[d3==0] <- NA -->
<!--   d_EpiEstim[,-1] <- d_EpiEstim[,-1]*d3 -->

<!--   # d_joint <- d_joint[match(d_EpiEstim$date,d_joint$date),] -->

<!--   d_joint <- tidyr::gather(d_joint,region,R,regions) -->
<!--   d_EpiEstim <- tidyr::gather(d_EpiEstim,region,R,regions) -->

<!--   d_12 <- merge(x = d_EpiEstim, y = d_joint, by = c('date','region'),all = TRUE) -->
<!--   d_12 <- d_12[-which(is.na(d_12$R.x+d_12$R.y)),] -->

<!--   if(i==1){ -->
<!--     d_tot <- d_12 -->
<!--   }else{ -->
<!--     d_tot <- rbind(d_tot,d_12) -->
<!--   } -->

<!--   g <- ggplot(d_12, aes(R.x,R.y)) +   -->
<!--     xlab('Rt (EpiEstim)') +  -->
<!--     ylab('Rt (multi)') + -->
<!--     stat_bin2d(bins=25) +  -->
<!--     xlim(0,2) + ylim(0,2) + -->
<!--     scale_fill_gradientn(colours=r) +  -->
<!--     geom_abline(intercept = 0,slope = 1,col='red3')  -->
<!--   print(g) -->

<!--   SS_tot <- sum((d_12$R.x - mean(d_12$R.x))^2) -->
<!--   SS_res <- sum((d_12$R.x-d_12$R.y)^2) -->
<!--   print(1-SS_res/SS_tot) -->
<!-- } -->

<!--   g <- ggplot(d_tot, aes(R.x,R.y)) +   -->
<!--     xlab('Rt (EpiEstim)') +  -->
<!--     ylab('Rt (multi)') + -->
<!--     stat_bin2d(bins=25) +  -->
<!--     xlim(0,2) + ylim(0,2) + -->
<!--     scale_fill_gradientn(colours=r) +  -->
<!--     geom_abline(intercept = 0,slope = 1,col='red3')  -->
<!--   print(g) -->

<!--   SS_tot <- sum((d_tot$R.x - mean(d_tot$R.x))^2) -->
<!--   SS_res <- sum((d_tot$R.x-d_tot$R.y)^2) -->
<!--   print(1-SS_res/SS_tot) -->

<!-- ``` -->




<!-- # test indepedantly wild-vs-alpha and wild-vs-beta -->

<!-- ```{r, joint_epiestim_epsilon} -->


<!-- Jestim_wild_alpha <- wrapper_joint_Rt(incid = incid[,,c(1,2)], -->
<!--                            t_start = t_start,  -->
<!--                            t_end = t_end,  -->
<!--                            n_intervals = n_intervals,  -->
<!--                            plot_Rt = TRUE,  -->
<!--                            plot_epsilon_trace = TRUE, -->
<!--                            plot_epsilon = TRUE ) -->
<!-- write.csv(Jestim_wild_alpha$Sum_epsilon, file = 'Rdata/epsilons_alpha.csv') -->

<!-- Jestim_wild_beta <- wrapper_joint_Rt(incid = incid[,,c(1,3)], -->
<!--                            t_start = t_start,  -->
<!--                            t_end = t_end,  -->
<!--                            n_intervals = n_intervals,  -->
<!--                            plot_Rt = TRUE,  -->
<!--                            plot_epsilon_trace = TRUE, -->
<!--                            plot_epsilon = TRUE ) -->

<!-- write.csv(Jestim_wild_beta$Sum_epsilon, file = 'Rdata/epsilons_beta.csv') -->

<!-- ``` -->



<!-- # by age classes -->

<!-- ```{r, age_class, fig.width=5, fig.height=8, eval = FALSE} -->

<!-- for(j in 1:(length(u_age)-1)){ -->
<!--   print(u_age[j]) -->

<!--   initial_res_age <- wrapper(age_group = u_age[j], regions = regions, plot_incidence = FALSE, -->
<!--                          variants = variants, t_window = t_window,  -->
<!--                          SI = SI_assumed, mean_prior = mean_prior, -->
<!--                          std_prior = std_prior, n_sample_R = n_sample_R) -->

<!--   selection_age <- select_Rt_get_median_samples(th = 0.2,  -->
<!--                                             EpiEstim_Rt = initial_res_age$EpiEstim_Rt, -->
<!--                                             regions = regions,  -->
<!--                                             variants = variants, -->
<!--                                             SI = SI_assumed, -->
<!--                                             trim = 0.99) -->
<!--   selection_age$summary_select -->


<!--   ep <- plot_hist_dist(x = selection_age$samples_Rts, x_sum = selection_age$summary_select, keep=TRUE) -->

<!--   for(i in 1:3){ -->
<!--     temp <- round(quantile(ep[[i]],c(0.5,.025,.975),na.rm=TRUE),digits = 2) -->
<!--     res_epsi[j,1+i] <- paste0(temp[1],' ; 95%CrI[',temp[2],' ; ',temp[3],']') -->
<!--   }      -->

<!-- } -->

<!-- ``` -->

