
---
title: "multi - french"
author: "Imperial College"
---


```{r echo = FALSE}
library(knitr)
opts_chunk$set(fig.path='figs/task4/', fig.keep='high',
               dev=c('png'), fig.width=8, fig.height=5, cache=FALSE,
               tidy=FALSE, warning=FALSE, fig.show="asis"
 	       )

library(ggplot2)
library(gridExtra)
library(RColorBrewer)
rf <- colorRampPalette(rev(brewer.pal(8,'Spectral')))
r <- rf(32)


###########################################################################
###########################################################################


errb <- function(d1,d2,title){
  d <- rbind(d1,d2)
  d$x <- rep(nrow(d1):1,2)+rep(c(.2,-.2),each=nrow(d1))
  d$methods <- rep(c('joint-EpiEstim','EpiEstim'),each=nrow(d1))
  
 
  
  #
  p <- ggplot(d, aes(x=med, y=x , fill=methods, color=methods)) + 
    geom_point() +
    geom_errorbarh(aes(xmin=low, xmax=up),height = .1) +
    scale_color_manual(values = c('blue3','DarkOrange3')) +
    labs(x="Effective Transmission Advantage", y = "") +
    scale_y_continuous(breaks=1:nrow(d1),labels = rev(d1$name)) +
    scale_x_continuous(limits = c(0,3)) +
    ggtitle(title) +
    geom_vline(xintercept=c(1), linetype="dashed",color='grey50') +
    geom_hline(yintercept = c(4.5,nrow(d1)-4+3.5), linetype="dashed", color='grey50') +
    theme_minimal() +
    theme(
      text = element_text(size = 12),
      legend.position="bottom"
    ) 
  return(p)
}


###########################################################################
###########################################################################


heatplot<- function(x,dealing_with,xlab,ylab,title,epsilon){
  
  # remove those not selected
  Rem <- x[[dealing_with[1]]]$Rt_incl[,-1] * x[[dealing_with[2]]]$Rt_incl[,-1]
  
  # get Rts
  x1 <- x[[dealing_with[1]]]$Rt_s
  for(i in 1:dim(x1)[3]){
    x1[,,i] <- as.matrix(x1[,,i]*Rem)
  }
  
  x2 <- x[[dealing_with[2]]]$Rt_s
  for(i in 1:dim(x1)[3]){
    x2[,,i] <- as.matrix(x2[,,i]*Rem)
  }
  x <- data.frame(x=c(x1),
                  y = c(x2))
  
  x2 <- seq(0,as.numeric(max(x,na.rm=TRUE)),length.out=10)
  d2 <- data.frame(x = x2,
                   y = as.numeric(epsilon[1])*x2,
                  ylower = as.numeric(epsilon[2])*x2,
                  yupper = as.numeric(epsilon[3])*x2)
  
  # epsilon <- Jestim_fr$epsilon$wild_alpha[1,2:4]
  p <- ggplot(x, aes(x,y)) +  
    xlab(paste0(xlab)) +
    ylab(paste0(ylab)) +
    stat_bin2d(bins=25) +
    scale_fill_gradientn(colours=r) +
    geom_abline(intercept = 0,slope = 1,col='grey50',linetype="dotted") +
    scale_x_continuous(expand = c(0, 0), limits = c(0,max(x,na.rm=TRUE))) +
    scale_y_continuous(expand = c(0, 0), limits = c(0,max(x,na.rm=TRUE))) +
    ggtitle(title) +
    geom_abline(slope=as.numeric(epsilon[1]),intercept = 0,color='DarkOrange3')+
    geom_abline(slope=as.numeric(epsilon[2]),intercept = 0,color='DarkOrange3',linetype="dashed")+
    geom_abline(slope=as.numeric(epsilon[3]),intercept = 0,color='DarkOrange3',linetype="dashed")

  
  return(p)
}

###########################################################################
###########################################################################

plotSI <- function(I, Rt1, Rt2, k, periods){
  
  variants <- names(I)
  x <- I[[1]]$date
  y <- I[[1]][,k+1]
  for(i in 2:length(I)){
    y <- cbind(y,I[[i]][,k+1])
  }
  
  cols=c('black','blue3','red3','')
  cols2 <- c(rgb(0,0,0,.1),rgb(0,0,1,.1),rgb(1,0,0,.1))
  # incidence
  x <- I[[1]]$date
  y <- I[[1]][,k+1]
  for(i in 2:length(I)){
    y <- cbind(y,I[[i]][,k+1])
  }
  # plot
  plot(x,y[,1],type='l',
       col = cols[1],
       main=(names(I[[1]][k+1])),
       bty = 'n',
       xlab = '',ylab = 'Incidence',
       ylim=c(0,max(y,na.rm=TRUE)))
  for (i in 2:ncol(y)){
    lines(x,y[,i],col = cols[i])
  }
  legend('topleft',legend = variants,
         lwd=2,col=cols[1:length(variants)],
         bty='n')
  abline(v = x[periods$intervals[c(3,4,5)]],col = 'grey50',lty=2)
  
  # Rt naive
  Rt <- Rt1
  y <- Rt[[1]]$Rt_m[,k+1]
  ylow <- Rt[[1]]$Rt_low[,k+1]
  yhigh <- Rt[[1]]$Rt_up[,k+1]
  
  for(i in 2:length(I)){
    y <- cbind(y,Rt[[i]]$Rt_m[,k+1])
    ylow <- cbind(ylow,Rt[[i]]$Rt_low[,k+1])
    yhigh <- cbind(yhigh,Rt[[i]]$Rt_up[,k+1])
  }
  f <- which(!is.na(y[,1]))
  #plot
  for(i in 1:length(I)){
    if (i==1){
      plot(x,y[,1],
           bty = 'n',
           xlab = '',ylab = 'Rt - EpiEstim',
           type = 'l',col=cols[1],
           main = '',
           ylim = c(0, 3) )
      abline(h = 1,lty=2,col='grey50')
    }else{
      lines(x,y[,i],col=cols[i])
    }
    polygon(c(x[f],rev(x[f])), c(ylow[f,i],rev(yhigh[f,i])),
            col = cols2[i],
            border = NA)
    # selected
    lines(x,
          rep(3,length(x))-i*.2,
          type = 'p',col=cols[i],
          pch='-',cex=0.5)
    
    lines(x[which(Rt[[1]]$Rt_incl[,k+1]==1)],
          rep(3,length(x))[which(Rt[[1]]$Rt_incl[,k+1]==1)]-i*.2,
          type = 'p',col=cols[i],
          pch=15,cex=0.5)
  }
  abline(v = x[periods$intervals[c(3,4,5)]],col = 'grey50',lty=2)
  
  # Rt from joint
  Rt <- Rt2
  cols <- RColorBrewer::brewer.pal(length(Rt),name = 'Dark2')
  cols2 <- yarrr::transparent(cols, trans.val = .9)
  
  y <- Rt[[1]]$median[,k]
  ylow <- Rt[[1]]$low[,k]
  yhigh <- Rt[[1]]$high[,k]
  
  for(i in 2:length(Rt)){
    y <- cbind(y,Rt[[i]]$median[,k])
    ylow <- cbind(ylow,Rt[[i]]$low[,k])
    yhigh <- cbind(yhigh,Rt[[i]]$high[,k])
  }
  
  #plot
  for(i in 1:length(Rt)){
    f <- which(!is.na(y[,i]))
    if (i==1){
      plot(x,y[,1],
           bty = 'n',
           xlab = '',ylab = 'Rt - Joint-EpiEstim',
           type = 'l',col=cols[1],
           main = '',
           ylim = c(0, 3) )
      abline(h = 1,lty=2,col='grey50')
    }else{
      lines(x,y[,i],col=cols[i])
    }
    polygon(c(x[f],rev(x[f])), c(ylow[f,i],rev(yhigh[f,i])),
            col = cols2[i],
            border = NA)
  }
  abline(v = x[periods$intervals[c(3,4,5)]],col = 'grey50',lty=2)
  
}
```

# load data

```{r}
# intial data
Epi_param <- readRDS('Rdata/Epi_param.rds')
I_fr <- readRDS(file = 'Rdata/I_fr.rds')
I_UK1 <- readRDS(file = 'Rdata/I_UK1.rds')
I_UK2 <- readRDS(file = 'Rdata/I_UK2.rds')
periods <- readRDS(file = 'Rdata/periods.rds')

# joint estimate of epsilons
Jestim_fr <- readRDS('Rdata/Jestim_fr.rds')
Jestim_UK1 <- readRDS('Rdata/Jestim_UK1.rds')
Jestim_UK2 <- readRDS('Rdata/Jestim_UK2.rds')

# naive epiestim
Rt_epi_fr <- readRDS('Rdata/Rt_epi_fr.rds')
Rt_epi_UK1 <- readRDS('Rdata/Rt_epi_UK1.rds')
Rt_epi_UK2 <- readRDS('Rdata/Rt_epi_UK2.rds')

# naive epsilon
naive_epsilon_fr <- readRDS( 'Rdata/naive_epsilon_fr.rds')
naive_epsilon_UK1 <- readRDS('Rdata/naive_epsilon_UK1.rds')
naive_epsilon_UK2 <- readRDS('Rdata/naive_epsilon_UK2.rds')

```


# errorbars of epsilons

## alpha - wild

```{r, epsilons1, fig.height=6, fig.width=8}


p <- errb(d1 = Jestim_fr$epsilon$wild_alpha,
          d2 = naive_epsilon_fr$sum_epsilon$wild_alpha,
          title = 'France - alpha vs. wild')

d1 <- Jestim_fr$epsilon$wild_alpha
d2 = naive_epsilon_fr$sum_epsilon$wild_alpha
print('median and 95')
d1[1,]
d2[1,]
print('across region')
quantile(d1[-c(1,20:23),2],c(.25,.75))
quantile(d2[-c(1,20:23),2],c(.25,.75),na.rm=TRUE)
print('time')
range(d1[-c(1:19),2],na.rm=TRUE)
range(d2[-c(1:19),2],na.rm=TRUE)


q <- errb(d1 = Jestim_UK1$epsilon$wild_alpha,
          d2 = naive_epsilon_UK1$sum_epsilon$wild_alpha,
          title = 'England - alpha vs. wild')

d1x = Jestim_UK1$epsilon$wild_alpha
d2x = naive_epsilon_UK1$sum_epsilon$wild_alpha
print('median and 95')
d1x[1,]
d2x[1,]
print('across region')
quantile(d1x[-c(1,9:12),2],c(.25,.75))
quantile(d2x[-c(1,9:12),2],c(.25,.75),na.rm=TRUE)
print('time')
range(d1x[-c(1:8),2],na.rm=TRUE)
range(d2x[-c(1:8),2],na.rm=TRUE)


grid.arrange(p, q, nrow = 1)



```

### Others

```{r, epsilons2, fig.height=6, fig.width=8}




p <- errb(d1 =  Jestim_fr$epsilon$`wild_beta/gamma`,
          d2 = naive_epsilon_fr$sum_epsilon$`wild_beta/gamma`,
          title = 'France - beta/gamma vs. wild')



d1 <- Jestim_fr$epsilon$`wild_beta/gamma`
d2 = naive_epsilon_fr$sum_epsilon$`wild_beta/gamma`
print('median and 95')
d1[1,]
d2[1,]
print('across region')
quantile(d1[-c(1,20:23),2],c(.25,.75))
quantile(d2[-c(1,20:23),2],c(.25,.75),na.rm=TRUE)
print('time')
range(d1[-c(1:19),2],na.rm=TRUE)
range(d2[-c(1:19),2],na.rm=TRUE)



q <- errb(d1 = Jestim_UK2$epsilon$alpha_delta,
          d2 = naive_epsilon_UK2$sum_epsilon$alpha_delta,
          title = 'England - delta vs. alpha')

d1x = Jestim_UK2$epsilon$alpha_delta
d2x = naive_epsilon_UK2$sum_epsilon$alpha_delta
print('median and 95')
d1x[1,]
d2x[1,]
print('across region')
quantile(d1x[-c(1,9:12),2],c(.25,.75))
quantile(d2x[-c(1,9:12),2],c(.25,.75),na.rm=TRUE)
print('time')
range(d1x[-c(1:8),2],na.rm=TRUE)
range(d2x[-c(1:8),2],na.rm=TRUE)

grid.arrange(p, q, nrow = 1)



```


# heatmap of Rts

## alpha wild

```{r, heatmap_Rts1, fig.height=5, fig.width=10}

p <- heatplot(x = Rt_epi_fr,
              dealing_with = c(1,2),
              xlab = 'Rt - wild',
              ylab = 'Rt - alpha',
              title = 'France',
              epsilon = Jestim_fr$epsilon$wild_alpha[1,2:4])

q <- heatplot(x = Rt_epi_UK1,
              dealing_with = c(1,2),
              xlab = 'Rt - wild',
              ylab = 'Rt - alpha',
              title = 'England',
              epsilon = Jestim_UK1$epsilon$wild_alpha[1,2:4])

grid.arrange(p, q, nrow = 1)
```


## others


```{r, heatmap_Rts2, fig.height=5, fig.width=14}

p <- heatplot(x = Rt_epi_fr,
              dealing_with = c(1,3),
              xlab = 'Rt - wild',
              ylab = 'Rt - beta/gamma',
              title = 'France',
              epsilon = Jestim_fr$epsilon$`wild_beta/gamma`[1,2:4])

p2 <- heatplot(x = Rt_epi_fr,
              dealing_with = c(2,3),
              xlab = 'Rt - alpha',
              ylab = 'Rt - beta/gamma',
              title = 'France',
              epsilon = rep(NA,3))

q <- heatplot(x = Rt_epi_UK2,
              dealing_with = c(1,2),
              xlab = 'Rt - alpha',
              ylab = 'Rt - delta',
              title = 'England',
              epsilon = Jestim_UK2$epsilon$alpha_delta[1,2:4])

grid.arrange(p, p2, q, nrow = 1)
```


# Supplemantary figures

## incidence

```{r, SI_incidence_fr, fig.height=6,fig.width=8}

layout(matrix(1:6,3,2,byrow = FALSE))

I <- I_fr
for(i in 1:(ncol(I[[1]])-1) ){
  plotSI(I = I,
         Rt1 = Rt_epi_fr,
         Rt2 = Jestim_fr$Sum_R, 
         k = i, 
         periods = periods$periods_fr)
}

```


```{r, SI_incidence_UK1, fig.height=6,fig.width=8}

layout(matrix(1:6,3,2,byrow = FALSE))

I <- I_UK1
for(i in 1:(ncol(I[[1]])-1) ){
  plotSI(I = I,
         Rt1 = Rt_epi_UK1,
         Rt2 = Jestim_UK1$Sum_R, 
         k = i, 
         periods = periods$periods_UK1)
}

```




```{r, SI_incidence_UK2, fig.height=6,fig.width=8}

layout(matrix(1:6,3,2,byrow = FALSE))

I <- I_UK2
for(i in 1:(ncol(I[[1]])-1) ){
  plotSI(I = I,
         Rt1 = Rt_epi_UK2,
         Rt2 = Jestim_UK2$Sum_R, 
         k = i, 
         periods = periods$periods_UK2)
}

```
